---
- name: Install required system packages for OctoPrint
  apt:
    pkg:
      - python3
      - python3-pip
      - python3-dev
      - python3-setuptools
      - python3-venv
      - git
      - libyaml-dev
      - build-essential
      - libffi-dev
      - libssl-dev
    state: latest
    update_cache: true

- name: Add {{ ansible_user }} user to tty and dialout groups
  user:
    name: "{{ ansible_user }}"
    groups: tty, dialout, video
    append: true

- name: Create OctoPrint directory
  file:
    path: "{{ octoprint_path }}"
    state: directory
    owner: "{{ ansible_user }}"
    group: "{{ ansible_user }}"

- name: Create {{ ansible_user }} config directory
  file:
    path: "{{ octoprint_config_path }}"
    state: directory
    owner: "{{ ansible_user }}"
    group: "{{ ansible_user }}"

- name: Install OctoPrint via pip
  pip:
    name: "{{ octoprint_url }}"
    virtualenv: "{{ venv_path }}"

- name: Install octoprint systemd service template
  template:
    src: octoprint.service.j2
    dest: /etc/systemd/system/octoprint.service
    owner: "{{ ansible_user }}"
  notify:
    - Restart octoprint service

- name: Change ownership of OctoPrint directory
  file:
    path: "{{ octoprint_path }}"
    state: directory
    recurse: true
    owner: "{{ ansible_user }}"
    group: "{{ ansible_user }}"

- name: Change ownership of config directory
  file:
    path: "{{ octoprint_config_path }}"
    state: directory
    recurse: true
    owner: "{{ ansible_user }}"
    group: "{{ ansible_user }}"
