---
- name: Install required system packages for HAProxy
  apt:
    pkg:
      - haproxy
    state: latest
    update_cache: true

- name: Copy HAProxy configurations
  copy:
    src: haproxy.cfg
    dest: /etc/haproxy/haproxy.cfg
  notify:
    - Restart haproxy service
