---
- name: Install required system packages for HAProxy
  apt:
    pkg:
      - haproxy
    state: latest
    update_cache: true

- name: Set HAProxy configurations
  template:
    src: haproxy.cfg.j2
    dest: /etc/haproxy/haproxy.cfg
  notify:
    - Restart haproxy service
