- name: Install Preheat Helper via pip
  pip:
    name: https://github.com/RoboMagus/OctoPrint-PreheatHelper/archive/master.zip
    virtualenv: "{{ venv_path }}"
  become: False

- name: Add Preheat Helper settings
  yedit:
    src: "{{octoprint_config_path}}/config.yaml"
    key: plugins.preheathelper
    value:
      last_bed_temp_setpoint: 60
      last_tool_temp_setpoint: 215
  notify:
    - Restart octoprint service
