---
- name: Add webcam actions to OctoPrint's system menu
  yedit:
    src: "{{octoprint_config_path}}/config.yaml"
    key: system.actions
    value:
      - action: streamon
        command: sudo service webcamd start
        confirm: false
        name: Start video stream
      - action: streamoff
        command: sudo service webcamd stop
        confirm: false
        name: Stop video stream
  notify:
    - Restart octoprint service
